### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by PaTricksStar** [luuuyi/SqueezeNext.PyTorch#2]
I found that there are some difference between your implementation and the author's:
1. the order of 1x3 and 3x1 convs is not changed ;
2. the way to down sample is different ;
3. the kernel size in the first conv.
Have you compare the performance of these networks?

**Comment by luuuyi** [comment]
@CK2Github Thanks for your reviewing.
For 1st question, may be i get confuse with the paper, but i just build my model from another repo(you can see it in README); You can switch the order as you want and test the network;
For 2nd and 3rd question, because i test my model in cifar10, cifar100 and tiny imagenet, the size of input image is smaller than ImageNet which the paper test on, so I make some difference on the first conv layer and down sample method.

**Comment by PaTricksStar** [comment]
Oh I see.
As the paper says under figure 2 :  'The order of 1 x 3 and 3 x 1 convolutions is changed throughout the network.', and so it does in the author's caffe prototxt.
So just change the order of 1x3 and 3x1 conv in two adjacent blocks.
Thanks for your code, still helpful.
